chore: update readme
diru1100/KVService pull request #30
Opened 2021-12-07 07:24 UTC by kurious-diru

add fullstop

2021-12-07 07:25 UTC, kurious-diru commented
/m

2021-12-07 07:27 UTC, kurious-diru commented on README.md
> +If interested, you can check out [my thought process in a seperate markdown file](thought_process.md).
why?

2021-12-07 07:27 UTC, kurious-diru commented
/m

2021-12-09 15:42 UTC, kurious-diru commented
/m

2021-12-09 16:15 UTC, kurious-diru commented
/m

2021-12-09 16:16 UTC, kurious-diru commented
/m

2021-12-09 16:28 UTC, kurious-diru commented
/m

2021-12-09 18:41 UTC, kurious-diru commented
/m

2021-12-09 18:53 UTC, kurious-diru commented
/m

2021-12-09 19:09 UTC, kurious-diru commented
/m

2021-12-09 19:10 UTC, kurious-diru commented
/m

2021-12-09 19:11 UTC, kurious-diru commented
/m

2021-12-09 19:12 UTC, kurious-diru commented
/m

2021-12-09 19:14 UTC, kurious-diru commented
/m

2021-12-09 19:14 UTC, kurious-diru commented
/m

2021-12-09 19:16 UTC, kurious-diru commented on README.md
> +If interested, you can check out [my thought process in a seperate markdown file](thought_process.md).
why?

2021-12-10 07:19 UTC, kurious-diru commented
/m

2021-12-10 07:38 UTC, kurious-diru commented
/m

2021-12-10 11:47 UTC, kurious-diru commented
test1

2021-12-10 11:48 UTC, kurious-diru commented
test1

2021-12-10 11:48 UTC, kurious-diru commented
test1

2021-12-10 11:49 UTC, kurious-diru commented
test1

2021-12-10 11:50 UTC, kurious-diru commented
test1

2021-12-10 11:51 UTC, kurious-diru commented
/m

2021-12-10 11:51 UTC, kurious-diru commented
test1

2021-12-10 11:52 UTC, kurious-diru commented
test1

2021-12-10 12:02 UTC, kurious-diru commented
test1

2021-12-10 12:05 UTC, kurious-diru commented
test2

2021-12-10 12:05 UTC, kurious-diru commented
oktest1

2021-12-10 12:07 UTC, kurious-diru commented
oktest2

2021-12-10 12:07 UTC, kurious-diru commented
/m

2021-12-10 12:08 UTC, kurious-diru commented
test1

2021-12-10 12:09 UTC, kurious-diru commented
oktest1

2021-12-10 12:12 UTC, me-diru commented
test1

2021-12-10 12:12 UTC, kurious-diru commented
test2

2021-12-10 12:13 UTC, kurious-diru commented
oktest1

2021-12-10 12:16 UTC, kurious-diru commented
oktest2

2021-12-10 12:18 UTC, kurious-diru commented
/m

2021-12-10 12:24 UTC, kurious-diru commented
/m

2021-12-10 12:24 UTC, kurious-diru commented
testok1

2021-12-10 12:43 UTC, kurious-diru commented
/m

2021-12-10 12:46 UTC, frezbo requested changes
test

2021-12-10 12:48 UTC, kurious-diru commented on README.md
> +If interested, you can check out [my thought process in a seperate markdown file](thought_process.md).
testt

2021-12-10 12:49 UTC, kurious-diru commented
oktest

2021-12-10 12:49 UTC, kurious-diru commented
oktest1

2021-12-10 12:51 UTC, kurious-diru commented
test1

2021-12-10 12:52 UTC, kurious-diru commented
test2

2021-12-10 12:52 UTC, kurious-diru commented
oktest1

2021-12-10 12:52 UTC, kurious-diru commented
oktest2

2021-12-10 13:18 UTC, frezbo approved these changes

2021-12-10 13:33 UTC, kurious-diru commented
/m

2021-12-10 13:34 UTC, kurious-diru commented
/m

2021-12-10 13:34 UTC, kurious-diru commented
/m

2021-12-10 13:35 UTC, kurious-diru commented
/merge

2021-12-10 13:35 UTC, kurious-diru commented
/m

2021-12-10 13:37 UTC, kurious-diru commented
/m

2021-12-10 13:54 UTC, kurious-diru commented
/m

2021-12-10 14:00 UTC, kurious-diru commented
/m

2021-12-10 14:01 UTC, kurious-diru commented
/m

2021-12-10 14:15 UTC, kurious-diru commented
/m

2021-12-10 14:20 UTC, kurious-diru commented
/m

2021-12-10 14:25 UTC, kurious-diru commented
/m

2021-12-10 14:51 UTC, kurious-diru commented
/m

2021-12-10 14:51 UTC, merged